Search.appendIndex(
    [
                {
            "fqsen": "\\DATABASE_CLASS_VERSION",
            "name": "DATABASE_CLASS_VERSION",
            "summary": "",
            "url": "namespaces/default.html#constant_DATABASE_CLASS_VERSION"
        },                {
            "fqsen": "\\DEBUG_TRACKER_BOTINFO",
            "name": "DEBUG_TRACKER_BOTINFO",
            "summary": "",
            "url": "namespaces/default.html#constant_DEBUG_TRACKER_BOTINFO"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\Database",
            "name": "Database",
            "summary": "Database.\u0020Second\u0020in\u0020the\u0020SiteClass\u0020framework",
            "url": "classes/bartonlp-SiteClass-Database.html"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\Database\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Database\u0020constructor.",
            "url": "classes/bartonlp-SiteClass-Database.html#method___construct"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\Database\u003A\u003AgetClassName\u0028\u0029",
            "name": "getClassName",
            "summary": "Get\u0020class\u0020Name",
            "url": "classes/bartonlp-SiteClass-Database.html#method_getClassName"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\Database\u003A\u003AgetVersion\u0028\u0029",
            "name": "getVersion",
            "summary": "Get\u0020the\u0020version\u0020of\u0020SiteClass",
            "url": "classes/bartonlp-SiteClass-Database.html#method_getVersion"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\Database\u003A\u003AupdateBots3\u0028\u0029",
            "name": "updateBots3",
            "summary": "Insert\/Update\u0020the\u0020MySql\u0020bots3\u0020table.",
            "url": "classes/bartonlp-SiteClass-Database.html#method_updateBots3"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\Database\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Returns\u0020the\u0020class\u0020name\u0020as\u0020a\u0020string.",
            "url": "classes/bartonlp-SiteClass-Database.html#method___toString"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\Database\u003A\u003A\u0024hitCount",
            "name": "hitCount",
            "summary": "",
            "url": "classes/bartonlp-SiteClass-Database.html#property_hitCount"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\Database\u003A\u003A\u0024myIp",
            "name": "myIp",
            "summary": "",
            "url": "classes/bartonlp-SiteClass-Database.html#property_myIp"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\Database\u003A\u003A\u0024nodb",
            "name": "nodb",
            "summary": "",
            "url": "classes/bartonlp-SiteClass-Database.html#property_nodb"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\Database\u003A\u003A\u0024noTrack",
            "name": "noTrack",
            "summary": "",
            "url": "classes/bartonlp-SiteClass-Database.html#property_noTrack"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\Database\u003A\u003A\u0024noGeo",
            "name": "noGeo",
            "summary": "",
            "url": "classes/bartonlp-SiteClass-Database.html#property_noGeo"
        },                {
            "fqsen": "\\PDO_CLASS_VERSION",
            "name": "PDO_CLASS_VERSION",
            "summary": "",
            "url": "namespaces/default.html#constant_PDO_CLASS_VERSION"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\dbPdo",
            "name": "dbPdo",
            "summary": "dbPdo.\u0020Bottom\u0020of\u0020the\u0020SiteClass\u0020framework",
            "url": "classes/bartonlp-SiteClass-dbPdo.html"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\dbPdo\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/bartonlp-SiteClass-dbPdo.html#method___construct"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\dbPdo\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Create\u0020a\u0020class\u0020from\u0020the\u0020caller",
            "url": "classes/bartonlp-SiteClass-dbPdo.html#method_create"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\dbPdo\u003A\u003AgetVersion\u0028\u0029",
            "name": "getVersion",
            "summary": "",
            "url": "classes/bartonlp-SiteClass-dbPdo.html#method_getVersion"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\dbPdo\u003A\u003AgetDbErrno\u0028\u0029",
            "name": "getDbErrno",
            "summary": "",
            "url": "classes/bartonlp-SiteClass-dbPdo.html#method_getDbErrno"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\dbPdo\u003A\u003AgetDbError\u0028\u0029",
            "name": "getDbError",
            "summary": "",
            "url": "classes/bartonlp-SiteClass-dbPdo.html#method_getDbError"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\dbPdo\u003A\u003Asql\u0028\u0029",
            "name": "sql",
            "summary": "Execute\u0020a\u0020Sql\u0020statment",
            "url": "classes/bartonlp-SiteClass-dbPdo.html#method_sql"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\dbPdo\u003A\u003AsqlPrepare\u0028\u0029",
            "name": "sqlPrepare",
            "summary": "Does\u0020a\u0020SQL\u0020prepare",
            "url": "classes/bartonlp-SiteClass-dbPdo.html#method_sqlPrepare"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\dbPdo\u003A\u003Aqueryfetch\u0028\u0029",
            "name": "queryfetch",
            "summary": "Does\u0020a\u0020sql\u0020query\u0020and\u0020returns\u0020all\u0020rows",
            "url": "classes/bartonlp-SiteClass-dbPdo.html#method_queryfetch"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\dbPdo\u003A\u003Afetchrow\u0028\u0029",
            "name": "fetchrow",
            "summary": "Fetch\u0020one\u0020row",
            "url": "classes/bartonlp-SiteClass-dbPdo.html#method_fetchrow"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\dbPdo\u003A\u003AgetLastInsertId\u0028\u0029",
            "name": "getLastInsertId",
            "summary": "Get\u0020the\u0020ID\u0020from\u0020the\u0020last\u0020insert",
            "url": "classes/bartonlp-SiteClass-dbPdo.html#method_getLastInsertId"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\dbPdo\u003A\u003AgetNumRows\u0028\u0029",
            "name": "getNumRows",
            "summary": "Get\u0020the\u0020number\u0020of\u0020rows",
            "url": "classes/bartonlp-SiteClass-dbPdo.html#method_getNumRows"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\dbPdo\u003A\u003AgetResult\u0028\u0029",
            "name": "getResult",
            "summary": "Get\u0020the\u0020last\u0020PDOStatement",
            "url": "classes/bartonlp-SiteClass-dbPdo.html#method_getResult"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\dbPdo\u003A\u003AgetErrorInfo\u0028\u0029",
            "name": "getErrorInfo",
            "summary": "Get\u0020error\u0020information\u0020from\u0020most\u0020recent\u0020query",
            "url": "classes/bartonlp-SiteClass-dbPdo.html#method_getErrorInfo"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\dbPdo\u003A\u003Aescape\u0028\u0029",
            "name": "escape",
            "summary": "Escape\u0020a\u0020string\u0020for\u0020PDO",
            "url": "classes/bartonlp-SiteClass-dbPdo.html#method_escape"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\dbPdo\u003A\u003AescapeDeep\u0028\u0029",
            "name": "escapeDeep",
            "summary": "A\u0020Deep\u0020escape\u0020replacement\u0020of\u0020apostrophies",
            "url": "classes/bartonlp-SiteClass-dbPdo.html#method_escapeDeep"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\dbPdo\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Macic\u0020toString\u0020return\u0020the\u0020class\u0020name",
            "url": "classes/bartonlp-SiteClass-dbPdo.html#method___toString"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\dbPdo\u003A\u003AgetColumnNames\u0028\u0029",
            "name": "getColumnNames",
            "summary": "",
            "url": "classes/bartonlp-SiteClass-dbPdo.html#method_getColumnNames"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\dbPdo\u003A\u003AmaketableFromRows\u0028\u0029",
            "name": "maketableFromRows",
            "summary": "",
            "url": "classes/bartonlp-SiteClass-dbPdo.html#method_maketableFromRows"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\dbPdo\u003A\u003A\u0024result",
            "name": "result",
            "summary": "The\u0020PDOstatement\u0020from\u0020the\u0020last\u0020sql\u0020query",
            "url": "classes/bartonlp-SiteClass-dbPdo.html#property_result"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\dbPdo\u003A\u003A\u0024lastQuery",
            "name": "lastQuery",
            "summary": "The\u0020last\u0020query\u0020that\u0020was\u0020executed",
            "url": "classes/bartonlp-SiteClass-dbPdo.html#property_lastQuery"
        },                {
            "fqsen": "\\SITE_CLASS_VERSION",
            "name": "SITE_CLASS_VERSION",
            "summary": "",
            "url": "namespaces/default.html#constant_SITE_CLASS_VERSION"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\SiteClass",
            "name": "SiteClass",
            "summary": "SiteClass.\u0020Top\u0020of\u0020the\u0020SiteClass\u0020framework.",
            "url": "classes/bartonlp-SiteClass-SiteClass.html"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\SiteClass\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "SiteClass\u0020constructor.",
            "url": "classes/bartonlp-SiteClass-SiteClass.html#method___construct"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\SiteClass\u003A\u003AgetVersion\u0028\u0029",
            "name": "getVersion",
            "summary": "Get\u0020the\u0020version\u0020of\u0020SiteClass",
            "url": "classes/bartonlp-SiteClass-SiteClass.html#method_getVersion"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\SiteClass\u003A\u003AgetHitCount\u0028\u0029",
            "name": "getHitCount",
            "summary": "getHitCount\u0028\u0029\u0020Gets\u0020the\u0020number\u0020of\u0020times\u0020someone\u0020visited\u0020our\u0020page",
            "url": "classes/bartonlp-SiteClass-SiteClass.html#method_getHitCount"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\SiteClass\u003A\u003AgetDoctype\u0028\u0029",
            "name": "getDoctype",
            "summary": "Get\u0020the\u0020\u0060\u003C\u0021DOCTYPE\u0020...\u003E\u0060",
            "url": "classes/bartonlp-SiteClass-SiteClass.html#method_getDoctype"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\SiteClass\u003A\u003AgetPageTopBottom\u0028\u0029",
            "name": "getPageTopBottom",
            "summary": "Get\u0020the\u0020top\u0020and\u0020bottom\u0020of\u0020the\u0020page",
            "url": "classes/bartonlp-SiteClass-SiteClass.html#method_getPageTopBottom"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\SiteClass\u003A\u003AgetPageTop\u0028\u0029",
            "name": "getPageTop",
            "summary": "Get\u0020the\u0020top\u0020of\u0020the\u0020page",
            "url": "classes/bartonlp-SiteClass-SiteClass.html#method_getPageTop"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\SiteClass\u003A\u003AgetPageHead\u0028\u0029",
            "name": "getPageHead",
            "summary": "Get\u0020the\u0020\u0060\u003Chead\u003E\u0060\u0020content",
            "url": "classes/bartonlp-SiteClass-SiteClass.html#method_getPageHead"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\SiteClass\u003A\u003AgetPageBanner\u0028\u0029",
            "name": "getPageBanner",
            "summary": "Get\u0020the\u0020banner\u0020information.",
            "url": "classes/bartonlp-SiteClass-SiteClass.html#method_getPageBanner"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\SiteClass\u003A\u003AgetPageFooter\u0028\u0029",
            "name": "getPageFooter",
            "summary": "Get\u0020the\u0020page\u0020footer",
            "url": "classes/bartonlp-SiteClass-SiteClass.html#method_getPageFooter"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\SiteClass\u003A\u003AgetCounterWigget\u0028\u0029",
            "name": "getCounterWigget",
            "summary": "Get\u0020the\u0020footer\u0020counter\u0020widget",
            "url": "classes/bartonlp-SiteClass-SiteClass.html#method_getCounterWigget"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\SiteClass\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Get\u0020the\u0020class\u0020name",
            "url": "classes/bartonlp-SiteClass-SiteClass.html#method___toString"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\SiteClass\u003A\u003AresolveCssAndFiletime\u0028\u0029",
            "name": "resolveCssAndFiletime",
            "summary": "Adds\u0020a\u0020cache\u0020buster\u0020to\u0020the\u0020css\u0020file",
            "url": "classes/bartonlp-SiteClass-SiteClass.html#method_resolveCssAndFiletime"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\SiteClass\u003A\u003A\u0024count",
            "name": "count",
            "summary": "Whether\u0020to\u0020display\u0020the\u0020hit\u0020counter\u0020widget.",
            "url": "classes/bartonlp-SiteClass-SiteClass.html#property_count"
        },                {
            "fqsen": "\\bartonlp\\SiteClass\\SiteClass\u003A\u003A\u0024doctype",
            "name": "doctype",
            "summary": "The\u0020document\u0020type\u0020declaration\u0020\u0028e.g.,\u0020\u0060\u003C\u0021DOCTYPE\u0020html\u003E\u0060\u0029.",
            "url": "classes/bartonlp-SiteClass-SiteClass.html#property_doctype"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\bartonlp\\SiteClass",
            "name": "SiteClass",
            "summary": "",
            "url": "namespaces/bartonlp-siteclass.html"
        },                {
            "fqsen": "\\bartonlp",
            "name": "bartonlp",
            "summary": "",
            "url": "namespaces/bartonlp.html"
        }            ]
);
